### ISSUE TITLE
Documentation: wrong function name in Gauge/CommonGauge examples?

### ISSUE THREAD

**Issue by Zagrebelin** [belousovalex/prometheus_redis_client#1]
May be i'm wrong, but Gauge/CommonGauge has a `.set()` method, but there is an `.observe()` in documentation.

**Comment by belousovalex** [comment]
> May be i'm wrong, but Gauge/CommonGauge has a `.set()` method, but there is an `.observe()` in documentation.

You are right. I fixed it. Thanks for report!
